name: Node Sync & Publish
on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行
  workflow_dispatch:

concurrency: 
  group: node-sync-${{ github.ref }}
  cancel-in-progress: true

jobs:
  process-nodes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: 'v2ray-repo'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          cd v2ray-repo
          pip install -r requirements.txt

      - name: Run node processing
        env:
          SOURCE_URLS: ${{ secrets.SOURCE_URLS }}
        run: |
          cd v2ray-repo
          python -m src.fetcher
          python -m src.processor
          python -m src.tester
          python -m src.filter
          python -m src.generator

      - name: Commit and push changes
        run: |
          cd v2ray-repo
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add subscription.txt REPORT.md
          git commit -m "Update: $(date +'%Y%m%d-%H%M%S')"
          git push
